### ISSUE TITLE
Can't receive f1.2 transactions 

### ISSUE THREAD

**Issue by kafcioo** [agile-ventures/TaaS#1]
When I tried to catch event/ transaction when interacting with f1.2 contract (mint function), Getting error showed below: 

![image](https://user-images.githubusercontent.com/9467225/70984262-106bf700-20b2-11ea-9dff-41f80bbb86b3.png)

Using Lorenz f1.2 smart contract described here: 
https://assets.tqtezos.com/quickstart/2-index

**Comment by andrewpaulicek** [comment]
Can you please attach the json of that block, so we can debug on our side?

**Comment by kafcioo** [comment]
Thanks for such a quick replay.

How do I get a block in Json format?, I'm using sandbox version of tezos node described here: 
https://assets.tqtezos.com/sandbox-quickstart

**Comment by andrewpaulicek** [comment]
using the RPC, for example 
`curl http://127.0.0.1/chains/main/blocks/1607 > block.json`

**Comment by kafcioo** [comment]
Could you please send me invite link to the slack channel

**Comment by andrewpaulicek** [comment]
invite sent

**Comment by kafcioo** [comment]
I didn't receive it, possibly because my GitHub email is different from my slack email. The email address that I use with my slack is: damian.klepacki@globacap.com

**Comment by andrewpaulicek** [comment]
we have published new docker images, can you please try it now?
will update the source as well, once confirmed on your side.

docker pull tezoslive/agileventurestezpusherweb:latest
you should get this one
sha256:07ebdec89bd06818b5a94ed900714a61da3dff1b7863a15caf9c90a13991c13f

**Comment by kafcioo** [comment]
Issue fixed and working as expected
