### ISSUE TITLE
Table of contents links are broken

### ISSUE THREAD

**Issue by itkach** [agile-ventures/TaaS#2]
E.g., "How to use" points to https://github.com/agile-ventures/TaaS/blob/master/#how-to-use and results in 404 page when clicked.

**Comment by andrewpaulicek** [comment]
Thanks for letting us know!

Apologies, we changed the structure little bit, so it is more readable at the main docs website [docs.tezoslive.io](https://docs.tezoslive.io) and apparently it broke the structure for github docs.

Fixed.
