### ISSUE TITLE
It is possible to listen to events on Carthagenet?

### ISSUE THREAD

**Issue by DalyIng** [agile-ventures/TaaS#5]
Hello, 

_Thank you for this great project!_

It is possible to listen to events on chain other than the **Mainnet**? **Carthagenet** for example?

**Comment by andrewpaulicek** [comment]
Hi,

it's not possible on the TezosLive.io endpoints currently. But you can just run your docker container on your side pointed at Carthagenet node.

Please take a look at documentation on how to do that
[https://docs.tezoslive.io/docs-getting-started/docs-using-docker/taas-websocket-in-docker](https://docs.tezoslive.io/docs-getting-started/docs-using-docker/taas-websocket-in-docker)

**Comment by DalyIng** [comment]
Hi @andrewpaulicek , thank you! I'll try that.
